"""AES-GCM Authenticated Encryption Infrastructure Service.

This module provides the `EncryptedMessage` data model and `AESService` class for
symmetric authenticated encryption using AES-128, AES-192, or AES-256 in GCM mode.
It accepts a `SharedSecretKey` generated by the E91 quantum protocol or raw byte keys.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
import hashlib
from typing import Union

from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes

from app.quantum.e91.shared_secret_key import SharedSecretKey


@dataclass(frozen=True)
class EncryptedMessage:
    """Container for AES-GCM encrypted message components."""

    ciphertext: bytes
    nonce: bytes
    authentication_tag: bytes
    algorithm: str
    key_size: int
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class AESService:
    """Infrastructure service providing authenticated AES-GCM encryption and decryption."""

    VALID_KEY_SIZES_BYTES = {16, 24, 32}  # AES-128, AES-192, AES-256

    def __init__(self, key: Union[SharedSecretKey, bytes, str], auto_hash_key: bool = False) -> None:
        """Initialize the AESService with a key.

        Args:
            key: A SharedSecretKey instance, raw bytes, or string.
            auto_hash_key: If True, derives a 256-bit key via SHA-256 if key size is not 16, 24, or 32 bytes.

        Raises:
            TypeError: If key is None.
            ValueError: If key size is invalid and auto_hash_key is False.
        """
        if key is None:
            raise TypeError("Key cannot be None.")

        key_bytes: bytes
        if isinstance(key, SharedSecretKey):
            key_bytes = key.byte_array
        elif isinstance(key, bytes):
            key_bytes = key
        elif isinstance(key, str):
            try:
                key_bytes = bytes.fromhex(key)
            except ValueError:
                key_bytes = key.encode("utf-8")
        else:
            raise TypeError(f"Unsupported key type: {type(key)}.")

        if len(key_bytes) not in self.VALID_KEY_SIZES_BYTES:
            if auto_hash_key:
                key_bytes = hashlib.sha256(key_bytes).digest()
            else:
                raise ValueError(
                    f"Invalid AES key length: {len(key_bytes)} bytes ({len(key_bytes) * 8} bits). "
                    f"Must be 16, 24, or 32 bytes (128, 192, or 256 bits)."
                )

        self._key_bytes = key_bytes
        self._key_size_bits = len(key_bytes) * 8
        self._algorithm = f"AES-{self._key_size_bits}-GCM"

    @property
    def key_bytes(self) -> bytes:
        """Return raw key bytes used by this service."""
        return self._key_bytes

    @property
    def key_size(self) -> int:
        """Return key size in bits (128, 192, or 256)."""
        return self._key_size_bits

    @property
    def algorithm(self) -> str:
        """Return algorithm string representation."""
        return self._algorithm

    def encrypt(self, plaintext: Union[str, bytes]) -> EncryptedMessage:
        """Encrypts plaintext using AES-GCM with a fresh random 12-byte nonce.

        Args:
            plaintext: Text or byte payload to encrypt.

        Returns:
            EncryptedMessage: Structured container with ciphertext, nonce, and auth tag.

        Raises:
            TypeError: If plaintext is None.
            ValueError: If plaintext is empty.
        """
        if plaintext is None:
            raise TypeError("Plaintext cannot be None.")

        payload_bytes: bytes
        if isinstance(plaintext, str):
            if not plaintext:
                raise ValueError("Plaintext string cannot be empty.")
            payload_bytes = plaintext.encode("utf-8")
        elif isinstance(plaintext, bytes):
            if not plaintext:
                raise ValueError("Plaintext bytes cannot be empty.")
            payload_bytes = plaintext
        else:
            raise TypeError(f"Unsupported plaintext type: {type(plaintext)}.")

        # Generate a fresh 12-byte (96-bit) random nonce for every encryption
        nonce = get_random_bytes(12)
        cipher = AES.new(self._key_bytes, AES.MODE_GCM, nonce=nonce)
        ciphertext, tag = cipher.encrypt_and_digest(payload_bytes)

        return EncryptedMessage(
            ciphertext=ciphertext,
            nonce=nonce,
            authentication_tag=tag,
            algorithm=self._algorithm,
            key_size=self._key_size_bits,
        )

    def decrypt(self, message: EncryptedMessage) -> bytes:
        """Decrypts an EncryptedMessage container and verifies authentication tag.

        Args:
            message: EncryptedMessage object containing ciphertext, nonce, and tag.

        Returns:
            bytes: Decrypted original plaintext payload bytes.

        Raises:
            TypeError: If message is None.
            ValueError: If authentication fails or ciphertext is corrupted.
        """
        if message is None:
            raise TypeError("EncryptedMessage cannot be None.")

        return self.decrypt_raw(message.ciphertext, message.nonce, message.authentication_tag)

    def decrypt_to_string(self, message: EncryptedMessage) -> str:
        """Decrypts an EncryptedMessage container and decodes to a UTF-8 string.

        Args:
            message: EncryptedMessage object.

        Returns:
            str: Decrypted UTF-8 string.
        """
        decrypted_bytes = self.decrypt(message)
        return decrypted_bytes.decode("utf-8")

    def decrypt_raw(self, ciphertext: bytes, nonce: bytes, tag: bytes) -> bytes:
        """Decrypts raw ciphertext, nonce, and authentication tag components.

        Args:
            ciphertext: Encrypted payload bytes.
            nonce: Nonce used during encryption.
            tag: GCM authentication tag.

        Returns:
            bytes: Decrypted plaintext bytes.

        Raises:
            ValueError: If tag verification fails or decryption fails.
        """
        if not ciphertext or not nonce or not tag:
            raise ValueError("Ciphertext, nonce, and authentication_tag must not be empty.")

        try:
            cipher = AES.new(self._key_bytes, AES.MODE_GCM, nonce=nonce)
            plaintext = cipher.decrypt_and_verify(ciphertext, tag)
            return plaintext
        except (ValueError, KeyError) as exc:
            raise ValueError(
                "Decryption failed: authentication tag verification failed. "
                "Message corrupted, tampered with, or wrong key used."
            ) from exc
