import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import {
  FileCode,
  KeyRound,
  ShieldCheck,
  Zap,
  CheckCircle2,
  ArrowRight
} from 'lucide-react';

export const PacketFlowAnimation: React.FC = () => {
  const [activeStage, setActiveStage] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setActiveStage((prev) => (prev + 1) % 5);
    }, 1800);
    return () => clearInterval(interval);
  }, []);

  const stages = [
    {
      id: 1,
      name: 'Payload Creation',
      icon: FileCode,
      desc: 'SCADA DNP3/Modbus packet generated by HMI operator',
      code: 'OPEN_BREAKER BRK_12'
    },
    {
      id: 2,
      name: 'E91 HKDF Encryption',
      icon: KeyRound,
      desc: 'AES-256-GCM authenticated encryption with 96-bit nonce',
      code: 'HKDF(Raw_Quantum_Key)'
    },
    {
      id: 3,
      name: '20-Stage Zero-Trust',
      icon: ShieldCheck,
      desc: 'HMAC-SHA256, RBAC, Nonce, Anti-Replay & Dynamic Trust (100.0)',
      code: '20/20 Checks Passed'
    },
    {
      id: 4,
      name: 'SCADA Execution',
      icon: Zap,
      desc: 'Substation RTU executes physical coil trip mechanism',
      code: 'Coil 0x05 TRIPPED'
    },
    {
      id: 5,
      name: 'Telemetry Feedback',
      icon: CheckCircle2,
      desc: 'Substation broadcasts 1s encrypted telemetry feedback',
      code: 'Voltage: 230V | Freq: 50Hz'
    }
  ];

  return (
    <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-5 shadow-md">
      <div className="flex items-center justify-between mb-4">
        <div>
          <h3 className="text-xs font-semibold text-slate-200 uppercase tracking-wider">
            Live Packet Stage Flow & Lifecycle Pipeline
          </h3>
          <p className="text-[11px] font-mono text-slate-400">
            Real-time end-to-end packet transmission from HMI creation to Substation execution
          </p>
        </div>
        <div className="flex items-center space-x-2 font-mono text-xs text-teal-400 bg-teal-950/60 border border-teal-800/60 px-3 py-1 rounded-full">
          <span className="w-2 h-2 rounded-full bg-teal-400 animate-ping"></span>
          <span>STAGE {activeStage + 1} OF 5 ACTIVE</span>
        </div>
      </div>

      {/* Animated Pipeline Stage Flow */}
      <div className="grid grid-cols-1 md:grid-cols-5 gap-3 relative">
        {stages.map((stg, idx) => {
          const Icon = stg.icon;
          const isActive = idx === activeStage;
          const isPassed = idx < activeStage;

          return (
            <motion.div
              key={stg.id}
              animate={{
                scale: isActive ? 1.03 : 1,
                borderColor: isActive ? '#14b8a6' : isPassed ? '#0f766e' : '#334155'
              }}
              transition={{ duration: 0.3 }}
              className={`p-3.5 rounded-xl border flex flex-col justify-between relative transition-all ${
                isActive
                  ? 'bg-slate-800 shadow-lg shadow-teal-500/10 border-teal-500'
                  : isPassed
                  ? 'bg-slate-900/80 border-teal-900/60 text-slate-300'
                  : 'bg-slate-950/60 border-slate-800 text-slate-500'
              }`}
            >
              <div className="flex items-center justify-between mb-2">
                <div
                  className={`p-2 rounded-lg ${
                    isActive
                      ? 'bg-teal-500 text-slate-950 font-bold'
                      : isPassed
                      ? 'bg-teal-950 text-teal-400'
                      : 'bg-slate-800 text-slate-600'
                  }`}
                >
                  <Icon className="w-4 h-4" />
                </div>
                <span className="font-mono text-[10px] text-slate-500">
                  STEP 0{stg.id}
                </span>
              </div>

              <div>
                <h4 className="text-xs font-semibold text-slate-200 mb-1">{stg.name}</h4>
                <p className="text-[10px] text-slate-400 leading-relaxed mb-2 font-sans">
                  {stg.desc}
                </p>
                <div className="font-mono text-[9px] bg-slate-950 border border-slate-800 text-teal-300 px-2 py-1 rounded">
                  {stg.code}
                </div>
              </div>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
};
