import React from "react";

export const HomePage: React.FC = () => {
  return (
    <div className="space-y-6">
      <div className="glass-panel p-8 rounded-2xl">
        <h1 className="font-title text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#00f0ff] to-[#9d4edd] mb-2">
          Welcome to EntangleNet QKD Studio
        </h1>
        <p className="text-[#8c9ba5] max-w-2xl text-sm leading-relaxed">
          Production-grade Quantum Key Distribution (QKD) simulation platform powered by Ekert 91
          entanglement verification, CHSH Bell inequality tests, and authenticated AES-GCM payload encryption.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="glass-panel p-6 rounded-2xl space-y-2">
          <div className="text-2xl">⚡</div>
          <h3 className="font-title font-semibold text-lg text-[#f0f4fc]">Studio Dashboard</h3>
          <p className="text-xs text-[#8c9ba5]">
            Run E91 protocol simulations, inspect real-time photon trajectories, and monitor CHSH violation scores.
          </p>
        </div>
        <div className="glass-panel p-6 rounded-2xl space-y-2">
          <div className="text-2xl">🌐</div>
          <h3 className="font-title font-semibold text-lg text-[#f0f4fc]">Network Graph</h3>
          <p className="text-xs text-[#8c9ba5]">
            Visualize multi-node quantum network repeaters, Alice/Bob terminals, and eavesdropper intercept nodes.
          </p>
        </div>
        <div className="glass-panel p-6 rounded-2xl space-y-2">
          <div className="text-2xl">🔒</div>
          <h3 className="font-title font-semibold text-lg text-[#f0f4fc]">AES-256-GCM</h3>
          <p className="text-xs text-[#8c9ba5]">
            Test post-quantum data payload encryption using shared secret keys generated by quantum non-locality.
          </p>
        </div>
      </div>
    </div>
  );
};
