from enum import Enum

class WSEventType(str, Enum):
    """WebSocket Broadcast Event Identifiers."""
    SESSION_CREATED = "SESSION_CREATED"
    CHANNEL_CONNECTED = "CHANNEL_CONNECTED"
    SESSION_READY = "SESSION_READY"
    SESSION_ACTIVATED = "SESSION_ACTIVATED"
    SESSION_TERMINATED = "SESSION_TERMINATED"
    TELEMETRY_UPDATE = "TELEMETRY_UPDATE"
    QUANTUM_STARTED = "QUANTUM_STARTED"
    BELL_PAIR_GENERATED = "BELL_PAIR_GENERATED"
    BASES_GENERATED = "BASES_GENERATED"
    MEASUREMENTS_COMPLETED = "MEASUREMENTS_COMPLETED"
    RAW_RESULTS_READY = "RAW_RESULTS_READY"


